### ISSUE TITLE
Implement Rust version of pad_to_multiple_of_4() function

### ISSUE THREAD

**Issue by jhodapp** [Jim-Hodapp-Coaching/esp32-pico-wifi#9]
Implement a Rust version of the C++ method from Pimoroni's reference code: https://github.com/pimoroni/pimoroni-pico/blob/main/drivers/esp32spi/spi_drv.cpp#L304

**Comment by bortyr** [comment]
Hey @jhodapp , don't we have it resolved ? From master branch: https://github.com/Jim-Hodapp-Coaching/esp32-pico-wifi/blob/master/src/main.rs#L403

**Comment by jhodapp** [comment]
Moving this issue to closed since it's now implemented.
